
export enum NQSArea {
  QA1 = 'QA1: Educational Program and Practice',
  QA2 = 'QA2: Children\'s Health and Safety',
  QA3 = 'QA3: Physical Environment',
  QA4 = 'QA4: Staffing Arrangements',
  QA5 = 'QA5: Relationships with Children',
  QA6 = 'QA6: Collaborative Partnerships',
  QA7 = 'QA7: Governance and Leadership'
}

export interface TimelineStep {
  title: string;
  description: string;
  estimatedDuration: string;
  resourcesNeeded: string[];
}

export interface PlannerGoal {
  id: string;
  area: NQSArea;
  statement: string;
  timeline: TimelineStep[];
  createdAt: Date;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  groundingSources?: { title: string; uri: string }[];
}

export enum AppView {
  DASHBOARD = 'DASHBOARD',
  OBSERVATION = 'OBSERVATION',
  NEWSLETTER = 'NEWSLETTER',
  QIP_PLANNER = 'QIP_PLANNER',
  COMPLIANCE = 'COMPLIANCE',
  ASSISTANT = 'ASSISTANT',
  STUDIO = 'STUDIO',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  ACTIVITY_PLANNER = 'ACTIVITY_PLANNER',
  ACTIVITY_LIBRARY = 'ACTIVITY_LIBRARY',
  DEVELOPMENT_REPORT = 'DEVELOPMENT_REPORT',
  CRITICAL_REFLECTION = 'CRITICAL_REFLECTION',
  PHILOSOPHY = 'PHILOSOPHY',
  PLANNING_CYCLE = 'PLANNING_CYCLE',
  EYLF_REFERENCE = 'EYLF_REFERENCE',
  SCHOOL_READINESS = 'SCHOOL_READINESS',
  ROUTINE_MANAGER = 'ROUTINE_MANAGER',
  ASSESSMENT_RATING = 'ASSESSMENT_RATING',
  FLOOR_PLAN = 'FLOOR_PLAN',
  SAFETY_CENTER = 'SAFETY_CENTER',
  DAILY_CARE = 'DAILY_CARE',
  CHILD_PROTECTION = 'CHILD_PROTECTION',
  CODE_OF_CONDUCT = 'CODE_OF_CONDUCT',
  MEDICAL_MANAGER = 'MEDICAL_MANAGER',
  OPERATIONAL_LOG = 'OPERATIONAL_LOG',
  DIRECTOR_OFFICE = 'DIRECTOR_OFFICE',
  RECEPTION = 'RECEPTION',
  SUBSCRIPTION = 'SUBSCRIPTION',
  LEGAL = 'LEGAL',
  INCIDENT_REPORTS = 'INCIDENT_REPORTS',
  ROOM_MANAGER = 'ROOM_MANAGER',
  STAFF_ROSTER = 'STAFF_ROSTER',
  EXCURSION_MANAGER = 'EXCURSION_MANAGER',
  SUSTAINABILITY_TRACKER = 'SUSTAINABILITY_TRACKER',
  MEDICATION_LOG = 'MEDICATION_LOG',
  PARENT_PORTAL = 'PARENT_PORTAL',
  INVENTORY = 'INVENTORY',
  ASSET_REGISTER = 'ASSET_REGISTER',
  CCS_ESTIMATOR = 'CCS_ESTIMATOR',
  EXPENSE_TRACKER = 'EXPENSE_TRACKER',
  TRANSITION_STATEMENTS = 'TRANSITION_STATEMENTS',
  CULTURAL_AUDIT = 'CULTURAL_AUDIT',
  INVOICING_SYSTEM = 'INVOICING_SYSTEM',
  STAFF_QUALIFICATIONS = 'STAFF_QUALIFICATIONS',
  CHEF_STATION = 'CHEF_STATION',
  SLEEP_TRACKER = 'SLEEP_TRACKER',
  OCCUPANCY_ANALYTICS = 'OCCUPANCY_ANALYTICS',
  WAITLIST_MANAGER = 'WAITLIST_MANAGER',
  EMERGENCY_HUB = 'EMERGENCY_HUB',
  POLICY_PORTAL = 'POLICY_PORTAL',
  HEALTH_COMPLIANCE = 'HEALTH_COMPLIANCE',
  MAINTENANCE_LOG = 'MAINTENANCE_LOG',
  PD_PORTFOLIO = 'PD_PORTFOLIO',
  CURRICULUM_BOARD = 'CURRICULUM_BOARD',
  PARENT_MESSAGES = 'PARENT_MESSAGES',
  STAFF_ONBOARDING = 'STAFF_ONBOARDING',
  DIRECTOR_GENERAL_DASHBOARD = 'DIRECTOR_GENERAL_DASHBOARD',
  COMPLIANCE_ALERTS = 'COMPLIANCE_ALERTS',
  RESOURCE_BOOKING = 'RESOURCE_BOOKING',
  WELLBEING_TRENDS = 'WELLBEING_TRENDS',
  REQUIRED_TRAINING = 'REQUIRED_TRAINING',
  FAMILY_AUDIT_LOG = 'FAMILY_AUDIT_LOG',
  INCLUSION_SUPPORT = 'INCLUSION_SUPPORT',
  CHILD_PORTFOLIO = 'CHILD_PORTFOLIO',
  COMMUNITY_HUB = 'COMMUNITY_HUB',
  PROFESSIONAL_STANDARDS = 'PROFESSIONAL_STANDARDS',
  GREEN_AUDIT = 'GREEN_AUDIT',
  MARKETING_STUDIO = 'MARKETING_STUDIO',
  NQS_OVERVIEW = 'NQS_OVERVIEW',
  USER_SETTINGS = 'USER_SETTINGS',
  SYSTEM_AUDIT_LOG = 'SYSTEM_AUDIT_LOG',
  ENROLMENT_MANAGER = 'ENROLMENT_MANAGER',
  DIGITAL_JOURNAL = 'DIGITAL_JOURNAL',
  OCCUPANCY_DASHBOARD = 'OCCUPANCY_DASHBOARD',
  REVENUE_FORECASTING = 'REVENUE_FORECASTING',
  WALKTHROUGH_CHECKLIST = 'WALKTHROUGH_CHECKLIST',
  MONTESSORI_CURRICULUM = 'MONTESSORI_CURRICULUM',
  TERMS_OF_SERVICE = 'TERMS_OF_SERVICE',
  PRIVACY_POLICY = 'PRIVACY_POLICY',
  STAFF_TIMESHEET = 'STAFF_TIMESHEET'
}

export enum AgeGroup {
  BABIES = "0-12 Months",
  TODDLERS = "1-2 Years",
  JUNIOR = "2-3 Years",
  PRESCHOOL = "3-5 Years",
  SCHOOL_AGE = "5-6 Years"
}
